Update workflow build (#11)
* Update main.yml for Windows build

This commit updates the main.yml workflow file to enable building and testing the application on Windows.
It removes the unnecessary setup for Node.js and updates the versions of actions/checkout and actions/setup-go.
Also, it specifies the required Go version as 1.20 and includes a new step to build the application specifically for Windows (amd64).

* Fix build command in main.yml workflow

The build command in the `main.yml` workflow was failing with the error "CGO_ENABLED=0'
 is not recognized as a name of a cmdlet, function, script file, or executable program."
 This error occurred due to the incorrect syntax of the build command.
This commit fixes the build command by updating the syntax to properly set the necessary
 environment variables for building the application on Windows with the amd64 architecture.

* Fix main.yml to resolve workflow error

The build command has been modified to use the `set` command instead of the `$env` syntax
 to set environment variables in the PowerShell environment.

* Fix go-version on main.yml

This commit changes go-version to 1.x trying to resolve the Error: server\server_test.go:92:13: undefined: syscall.Kill

* Fix main.yml to resolve testing error

This commit reverts main.yml back to a similar version as to  when it was
created. The purpose of this commit is trying to get the workflow back
to a working state.
Steps modified from the original build:

- actions/checkout@v2 updated to @v3
- actions/setup-go@v2 updated to @v4
- run: go build -o endpoint main.go changed to run: go build -o endpoint -o build/endpoint main.go